enyo.depends(
	"Spinn/depends.js",
	"app/Utils.js",
	"app/database-enyo.js",
	"app/YouTube-model.js",
	"app/YouTubeApi.js",
	"app/TimeLine.js",
	"AddEditEntityDialog/depends.js",
	"app/YouTubeViewer.js",
	"app/YouTubeVideoDetails.js",
	"app/uTube.js"
);